package mnj.mfg.model.views;

import java.math.BigDecimal;

import mnj.mfg.model.entities.ReceiveDetailEOImpl;

import oracle.jbo.Row;
import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Mar 07 11:50:22 BDT 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ReceiveDetailVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        HeaderId {
            public Object get(ReceiveDetailVORowImpl obj) {
                return obj.getHeaderId();
            }

            public void put(ReceiveDetailVORowImpl obj, Object value) {
                obj.setHeaderId((Number)value);
            }
        }
        ,
        LineId {
            public Object get(ReceiveDetailVORowImpl obj) {
                return obj.getLineId();
            }

            public void put(ReceiveDetailVORowImpl obj, Object value) {
                obj.setLineId((Number)value);
            }
        }
        ,
        RecevingDetail {
            public Object get(ReceiveDetailVORowImpl obj) {
                return obj.getRecevingDetail();
            }

            public void put(ReceiveDetailVORowImpl obj, Object value) {
                obj.setRecevingDetail((Number)value);
            }
        }
        ,
        RecevingChallanNo {
            public Object get(ReceiveDetailVORowImpl obj) {
                return obj.getRecevingChallanNo();
            }

            public void put(ReceiveDetailVORowImpl obj, Object value) {
                obj.setRecevingChallanNo((String)value);
            }
        }
        ,
        RcvFromWashDate {
            public Object get(ReceiveDetailVORowImpl obj) {
                return obj.getRcvFromWashDate();
            }

            public void put(ReceiveDetailVORowImpl obj, Object value) {
                obj.setRcvFromWashDate((Date)value);
            }
        }
        ,
        WashRcvQty {
            public Object get(ReceiveDetailVORowImpl obj) {
                return obj.getWashRcvQty();
            }

            public void put(ReceiveDetailVORowImpl obj, Object value) {
                obj.setWashRcvQty((Number)value);
            }
        }
        ,
        MajorIssues {
            public Object get(ReceiveDetailVORowImpl obj) {
                return obj.getMajorIssues();
            }

            public void put(ReceiveDetailVORowImpl obj, Object value) {
                obj.setMajorIssues((String)value);
            }
        }
        ,
        ActionTaken {
            public Object get(ReceiveDetailVORowImpl obj) {
                return obj.getActionTaken();
            }

            public void put(ReceiveDetailVORowImpl obj, Object value) {
                obj.setActionTaken((String)value);
            }
        }
        ,
        CurrectionReqArea {
            public Object get(ReceiveDetailVORowImpl obj) {
                return obj.getCurrectionReqArea();
            }

            public void put(ReceiveDetailVORowImpl obj, Object value) {
                obj.setCurrectionReqArea((String)value);
            }
        }
        ,
        Remarks {
            public Object get(ReceiveDetailVORowImpl obj) {
                return obj.getRemarks();
            }

            public void put(ReceiveDetailVORowImpl obj, Object value) {
                obj.setRemarks((String)value);
            }
        }
        ,
        Attribute1 {
            public Object get(ReceiveDetailVORowImpl obj) {
                return obj.getAttribute1();
            }

            public void put(ReceiveDetailVORowImpl obj, Object value) {
                obj.setAttribute1((String)value);
            }
        }
        ,
        Attribute2 {
            public Object get(ReceiveDetailVORowImpl obj) {
                return obj.getAttribute2();
            }

            public void put(ReceiveDetailVORowImpl obj, Object value) {
                obj.setAttribute2((String)value);
            }
        }
        ,
        Attribute3 {
            public Object get(ReceiveDetailVORowImpl obj) {
                return obj.getAttribute3();
            }

            public void put(ReceiveDetailVORowImpl obj, Object value) {
                obj.setAttribute3((String)value);
            }
        }
        ,
        Attribute4 {
            public Object get(ReceiveDetailVORowImpl obj) {
                return obj.getAttribute4();
            }

            public void put(ReceiveDetailVORowImpl obj, Object value) {
                obj.setAttribute4((String)value);
            }
        }
        ,
        Attribute5 {
            public Object get(ReceiveDetailVORowImpl obj) {
                return obj.getAttribute5();
            }

            public void put(ReceiveDetailVORowImpl obj, Object value) {
                obj.setAttribute5((String)value);
            }
        }
        ,
        Attribute6 {
            public Object get(ReceiveDetailVORowImpl obj) {
                return obj.getAttribute6();
            }

            public void put(ReceiveDetailVORowImpl obj, Object value) {
                obj.setAttribute6((String)value);
            }
        }
        ,
        Attribute7 {
            public Object get(ReceiveDetailVORowImpl obj) {
                return obj.getAttribute7();
            }

            public void put(ReceiveDetailVORowImpl obj, Object value) {
                obj.setAttribute7((String)value);
            }
        }
        ,
        Attribute8 {
            public Object get(ReceiveDetailVORowImpl obj) {
                return obj.getAttribute8();
            }

            public void put(ReceiveDetailVORowImpl obj, Object value) {
                obj.setAttribute8((String)value);
            }
        }
        ,
        Attribute9 {
            public Object get(ReceiveDetailVORowImpl obj) {
                return obj.getAttribute9();
            }

            public void put(ReceiveDetailVORowImpl obj, Object value) {
                obj.setAttribute9((String)value);
            }
        }
        ,
        Attribute10 {
            public Object get(ReceiveDetailVORowImpl obj) {
                return obj.getAttribute10();
            }

            public void put(ReceiveDetailVORowImpl obj, Object value) {
                obj.setAttribute10((String)value);
            }
        }
        ,
        Attribute11 {
            public Object get(ReceiveDetailVORowImpl obj) {
                return obj.getAttribute11();
            }

            public void put(ReceiveDetailVORowImpl obj, Object value) {
                obj.setAttribute11((String)value);
            }
        }
        ,
        Attribute12 {
            public Object get(ReceiveDetailVORowImpl obj) {
                return obj.getAttribute12();
            }

            public void put(ReceiveDetailVORowImpl obj, Object value) {
                obj.setAttribute12((String)value);
            }
        }
        ,
        Attribute13 {
            public Object get(ReceiveDetailVORowImpl obj) {
                return obj.getAttribute13();
            }

            public void put(ReceiveDetailVORowImpl obj, Object value) {
                obj.setAttribute13((String)value);
            }
        }
        ,
        Attribute14 {
            public Object get(ReceiveDetailVORowImpl obj) {
                return obj.getAttribute14();
            }

            public void put(ReceiveDetailVORowImpl obj, Object value) {
                obj.setAttribute14((String)value);
            }
        }
        ,
        Attribute15 {
            public Object get(ReceiveDetailVORowImpl obj) {
                return obj.getAttribute15();
            }

            public void put(ReceiveDetailVORowImpl obj, Object value) {
                obj.setAttribute15((String)value);
            }
        }
        ,
        SalesorderId {
            public Object get(ReceiveDetailVORowImpl obj) {
                return obj.getSalesorderId();
            }

            public void put(ReceiveDetailVORowImpl obj, Object value) {
                obj.setSalesorderId((Number)value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(ReceiveDetailVORowImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(ReceiveDetailVORowImpl obj, Object value) {
                obj.setLastUpdateDate((Date)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(ReceiveDetailVORowImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(ReceiveDetailVORowImpl obj, Object value) {
                obj.setLastUpdatedBy((Number)value);
            }
        }
        ,
        CreationDate {
            public Object get(ReceiveDetailVORowImpl obj) {
                return obj.getCreationDate();
            }

            public void put(ReceiveDetailVORowImpl obj, Object value) {
                obj.setCreationDate((Date)value);
            }
        }
        ,
        CreatedBy {
            public Object get(ReceiveDetailVORowImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(ReceiveDetailVORowImpl obj, Object value) {
                obj.setCreatedBy((Number)value);
            }
        }
        ,
        OrgId {
            public Object get(ReceiveDetailVORowImpl obj) {
                return obj.getOrgId();
            }

            public void put(ReceiveDetailVORowImpl obj, Object value) {
                obj.setOrgId((Number)value);
            }
        }
        ,
        WashEmdPrintInvorg {
            public Object get(ReceiveDetailVORowImpl obj) {
                return obj.getWashEmdPrintInvorg();
            }

            public void put(ReceiveDetailVORowImpl obj, Object value) {
                obj.setWashEmdPrintInvorg((String)value);
            }
        }
        ,
        WashEmdPrintInv {
            public Object get(ReceiveDetailVORowImpl obj) {
                return obj.getWashEmdPrintInv();
            }

            public void put(ReceiveDetailVORowImpl obj, Object value) {
                obj.setWashEmdPrintInv((Number)value);
            }
        }
        ,
        WashType {
            public Object get(ReceiveDetailVORowImpl obj) {
                return obj.getWashType();
            }

            public void put(ReceiveDetailVORowImpl obj, Object value) {
                obj.setWashType((String)value);
            }
        }
        ,
        ProductionType {
            public Object get(ReceiveDetailVORowImpl obj) {
                return obj.getProductionType();
            }

            public void put(ReceiveDetailVORowImpl obj, Object value) {
                obj.setProductionType((String)value);
            }
        }
        ,
        RecevingDate {
            public Object get(ReceiveDetailVORowImpl obj) {
                return obj.getRecevingDate();
            }

            public void put(ReceiveDetailVORowImpl obj, Object value) {
                obj.setRecevingDate((Date)value);
            }
        }
        ,
        PocId {
            public Object get(ReceiveDetailVORowImpl obj) {
                return obj.getPocId();
            }

            public void put(ReceiveDetailVORowImpl obj, Object value) {
                obj.setPocId((BigDecimal)value);
            }
        }
        ,
        BpoId {
            public Object get(ReceiveDetailVORowImpl obj) {
                return obj.getBpoId();
            }

            public void put(ReceiveDetailVORowImpl obj, Object value) {
                obj.setBpoId((Number)value);
            }
        }
        ,
        ReciveSizeInseemVO {
            public Object get(ReceiveDetailVORowImpl obj) {
                return obj.getReciveSizeInseemVO();
            }

            public void put(ReceiveDetailVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LineHeaderEOView {
            public Object get(ReceiveDetailVORowImpl obj) {
                return obj.getLineHeaderEOView();
            }

            public void put(ReceiveDetailVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        RevBPOVO1 {
            public Object get(ReceiveDetailVORowImpl obj) {
                return obj.getRevBPOVO1();
            }

            public void put(ReceiveDetailVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        InvOrgVO1 {
            public Object get(ReceiveDetailVORowImpl obj) {
                return obj.getInvOrgVO1();
            }

            public void put(ReceiveDetailVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ProductionTypeVO1 {
            public Object get(ReceiveDetailVORowImpl obj) {
                return obj.getProductionTypeVO1();
            }

            public void put(ReceiveDetailVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        WashTypeVO1 {
            public Object get(ReceiveDetailVORowImpl obj) {
                return obj.getWashTypeVO1();
            }

            public void put(ReceiveDetailVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        BPO_LOV1 {
            public Object get(ReceiveDetailVORowImpl obj) {
                return obj.getBPO_LOV1();
            }

            public void put(ReceiveDetailVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(ReceiveDetailVORowImpl object);

        public abstract void put(ReceiveDetailVORowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int HEADERID = AttributesEnum.HeaderId.index();
    public static final int LINEID = AttributesEnum.LineId.index();
    public static final int RECEVINGDETAIL = AttributesEnum.RecevingDetail.index();
    public static final int RECEVINGCHALLANNO = AttributesEnum.RecevingChallanNo.index();
    public static final int RCVFROMWASHDATE = AttributesEnum.RcvFromWashDate.index();
    public static final int WASHRCVQTY = AttributesEnum.WashRcvQty.index();
    public static final int MAJORISSUES = AttributesEnum.MajorIssues.index();
    public static final int ACTIONTAKEN = AttributesEnum.ActionTaken.index();
    public static final int CURRECTIONREQAREA = AttributesEnum.CurrectionReqArea.index();
    public static final int REMARKS = AttributesEnum.Remarks.index();
    public static final int ATTRIBUTE1 = AttributesEnum.Attribute1.index();
    public static final int ATTRIBUTE2 = AttributesEnum.Attribute2.index();
    public static final int ATTRIBUTE3 = AttributesEnum.Attribute3.index();
    public static final int ATTRIBUTE4 = AttributesEnum.Attribute4.index();
    public static final int ATTRIBUTE5 = AttributesEnum.Attribute5.index();
    public static final int ATTRIBUTE6 = AttributesEnum.Attribute6.index();
    public static final int ATTRIBUTE7 = AttributesEnum.Attribute7.index();
    public static final int ATTRIBUTE8 = AttributesEnum.Attribute8.index();
    public static final int ATTRIBUTE9 = AttributesEnum.Attribute9.index();
    public static final int ATTRIBUTE10 = AttributesEnum.Attribute10.index();
    public static final int ATTRIBUTE11 = AttributesEnum.Attribute11.index();
    public static final int ATTRIBUTE12 = AttributesEnum.Attribute12.index();
    public static final int ATTRIBUTE13 = AttributesEnum.Attribute13.index();
    public static final int ATTRIBUTE14 = AttributesEnum.Attribute14.index();
    public static final int ATTRIBUTE15 = AttributesEnum.Attribute15.index();
    public static final int SALESORDERID = AttributesEnum.SalesorderId.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int ORGID = AttributesEnum.OrgId.index();
    public static final int WASHEMDPRINTINVORG = AttributesEnum.WashEmdPrintInvorg.index();
    public static final int WASHEMDPRINTINV = AttributesEnum.WashEmdPrintInv.index();
    public static final int WASHTYPE = AttributesEnum.WashType.index();
    public static final int PRODUCTIONTYPE = AttributesEnum.ProductionType.index();
    public static final int RECEVINGDATE = AttributesEnum.RecevingDate.index();
    public static final int POCID = AttributesEnum.PocId.index();
    public static final int BPOID = AttributesEnum.BpoId.index();
    public static final int RECIVESIZEINSEEMVO = AttributesEnum.ReciveSizeInseemVO.index();
    public static final int LINEHEADEREOVIEW = AttributesEnum.LineHeaderEOView.index();
    public static final int REVBPOVO1 = AttributesEnum.RevBPOVO1.index();
    public static final int INVORGVO1 = AttributesEnum.InvOrgVO1.index();
    public static final int PRODUCTIONTYPEVO1 = AttributesEnum.ProductionTypeVO1.index();
    public static final int WASHTYPEVO1 = AttributesEnum.WashTypeVO1.index();
    public static final int BPO_LOV1 = AttributesEnum.BPO_LOV1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public ReceiveDetailVORowImpl() {
    }

    /**
     * Gets ReceiveDetailEO entity object.
     * @return the ReceiveDetailEO
     */
    public ReceiveDetailEOImpl getReceiveDetailEO() {
        return (ReceiveDetailEOImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for HEADER_ID using the alias name HeaderId.
     * @return the HEADER_ID
     */
    public Number getHeaderId() {
        return (Number) getAttributeInternal(HEADERID);
    }

    /**
     * Sets <code>value</code> as attribute value for HEADER_ID using the alias name HeaderId.
     * @param value value to set the HEADER_ID
     */
    public void setHeaderId(Number value) {
        setAttributeInternal(HEADERID, value);
    }

    /**
     * Gets the attribute value for LINE_ID using the alias name LineId.
     * @return the LINE_ID
     */
    public Number getLineId() {
        return (Number) getAttributeInternal(LINEID);
    }

    /**
     * Sets <code>value</code> as attribute value for LINE_ID using the alias name LineId.
     * @param value value to set the LINE_ID
     */
    public void setLineId(Number value) {
        setAttributeInternal(LINEID, value);
    }

    /**
     * Gets the attribute value for RECEVING_DETAIL using the alias name RecevingDetail.
     * @return the RECEVING_DETAIL
     */
    public Number getRecevingDetail() {
        return (Number) getAttributeInternal(RECEVINGDETAIL);
    }

    /**
     * Sets <code>value</code> as attribute value for RECEVING_DETAIL using the alias name RecevingDetail.
     * @param value value to set the RECEVING_DETAIL
     */
    public void setRecevingDetail(Number value) {
        setAttributeInternal(RECEVINGDETAIL, value);
    }

    /**
     * Gets the attribute value for RECEVING_CHALLAN_NO using the alias name RecevingChallanNo.
     * @return the RECEVING_CHALLAN_NO
     */
    public String getRecevingChallanNo() {
        return (String) getAttributeInternal(RECEVINGCHALLANNO);
    }

    /**
     * Sets <code>value</code> as attribute value for RECEVING_CHALLAN_NO using the alias name RecevingChallanNo.
     * @param value value to set the RECEVING_CHALLAN_NO
     */
    public void setRecevingChallanNo(String value) {
        setAttributeInternal(RECEVINGCHALLANNO, value);
    }

    /**
     * Gets the attribute value for RCV_FROM_WASH_DATE using the alias name RcvFromWashDate.
     * @return the RCV_FROM_WASH_DATE
     */
    public Date getRcvFromWashDate() {
        return (Date) getAttributeInternal(RCVFROMWASHDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for RCV_FROM_WASH_DATE using the alias name RcvFromWashDate.
     * @param value value to set the RCV_FROM_WASH_DATE
     */
    public void setRcvFromWashDate(Date value) {
        setAttributeInternal(RCVFROMWASHDATE, value);
    }

    /**
     * Gets the attribute value for WASH_RCV_QTY using the alias name WashRcvQty.
     * @return the WASH_RCV_QTY
     */
    public Number getWashRcvQty() {
        return (Number) getAttributeInternal(WASHRCVQTY);
    }

    /**
     * Sets <code>value</code> as attribute value for WASH_RCV_QTY using the alias name WashRcvQty.
     * @param value value to set the WASH_RCV_QTY
     */
    public void setWashRcvQty(Number value) {
        setAttributeInternal(WASHRCVQTY, value);
    }

    /**
     * Gets the attribute value for MAJOR_ISSUES using the alias name MajorIssues.
     * @return the MAJOR_ISSUES
     */
    public String getMajorIssues() {
        return (String) getAttributeInternal(MAJORISSUES);
    }

    /**
     * Sets <code>value</code> as attribute value for MAJOR_ISSUES using the alias name MajorIssues.
     * @param value value to set the MAJOR_ISSUES
     */
    public void setMajorIssues(String value) {
        setAttributeInternal(MAJORISSUES, value);
    }

    /**
     * Gets the attribute value for ACTION_TAKEN using the alias name ActionTaken.
     * @return the ACTION_TAKEN
     */
    public String getActionTaken() {
        return (String) getAttributeInternal(ACTIONTAKEN);
    }

    /**
     * Sets <code>value</code> as attribute value for ACTION_TAKEN using the alias name ActionTaken.
     * @param value value to set the ACTION_TAKEN
     */
    public void setActionTaken(String value) {
        setAttributeInternal(ACTIONTAKEN, value);
    }

    /**
     * Gets the attribute value for CURRECTION_REQ_AREA using the alias name CurrectionReqArea.
     * @return the CURRECTION_REQ_AREA
     */
    public String getCurrectionReqArea() {
        return (String) getAttributeInternal(CURRECTIONREQAREA);
    }

    /**
     * Sets <code>value</code> as attribute value for CURRECTION_REQ_AREA using the alias name CurrectionReqArea.
     * @param value value to set the CURRECTION_REQ_AREA
     */
    public void setCurrectionReqArea(String value) {
        setAttributeInternal(CURRECTIONREQAREA, value);
    }

    /**
     * Gets the attribute value for REMARKS using the alias name Remarks.
     * @return the REMARKS
     */
    public String getRemarks() {
        return (String) getAttributeInternal(REMARKS);
    }

    /**
     * Sets <code>value</code> as attribute value for REMARKS using the alias name Remarks.
     * @param value value to set the REMARKS
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE1 using the alias name Attribute1.
     * @return the ATTRIBUTE1
     */
    public String getAttribute1() {
        return (String) getAttributeInternal(ATTRIBUTE1);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE1 using the alias name Attribute1.
     * @param value value to set the ATTRIBUTE1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE2 using the alias name Attribute2.
     * @return the ATTRIBUTE2
     */
    public String getAttribute2() {
        return (String) getAttributeInternal(ATTRIBUTE2);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE2 using the alias name Attribute2.
     * @param value value to set the ATTRIBUTE2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE3 using the alias name Attribute3.
     * @return the ATTRIBUTE3
     */
    public String getAttribute3() {
        return (String) getAttributeInternal(ATTRIBUTE3);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE3 using the alias name Attribute3.
     * @param value value to set the ATTRIBUTE3
     */
    public void setAttribute3(String value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE4 using the alias name Attribute4.
     * @return the ATTRIBUTE4
     */
    public String getAttribute4() {
        return (String) getAttributeInternal(ATTRIBUTE4);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE4 using the alias name Attribute4.
     * @param value value to set the ATTRIBUTE4
     */
    public void setAttribute4(String value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE5 using the alias name Attribute5.
     * @return the ATTRIBUTE5
     */
    public String getAttribute5() {
        return (String) getAttributeInternal(ATTRIBUTE5);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE5 using the alias name Attribute5.
     * @param value value to set the ATTRIBUTE5
     */
    public void setAttribute5(String value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE6 using the alias name Attribute6.
     * @return the ATTRIBUTE6
     */
    public String getAttribute6() {
        return (String) getAttributeInternal(ATTRIBUTE6);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE6 using the alias name Attribute6.
     * @param value value to set the ATTRIBUTE6
     */
    public void setAttribute6(String value) {
        setAttributeInternal(ATTRIBUTE6, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE7 using the alias name Attribute7.
     * @return the ATTRIBUTE7
     */
    public String getAttribute7() {
        return (String) getAttributeInternal(ATTRIBUTE7);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE7 using the alias name Attribute7.
     * @param value value to set the ATTRIBUTE7
     */
    public void setAttribute7(String value) {
        setAttributeInternal(ATTRIBUTE7, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE8 using the alias name Attribute8.
     * @return the ATTRIBUTE8
     */
    public String getAttribute8() {
        return (String) getAttributeInternal(ATTRIBUTE8);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE8 using the alias name Attribute8.
     * @param value value to set the ATTRIBUTE8
     */
    public void setAttribute8(String value) {
        setAttributeInternal(ATTRIBUTE8, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE9 using the alias name Attribute9.
     * @return the ATTRIBUTE9
     */
    public String getAttribute9() {
        return (String) getAttributeInternal(ATTRIBUTE9);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE9 using the alias name Attribute9.
     * @param value value to set the ATTRIBUTE9
     */
    public void setAttribute9(String value) {
        setAttributeInternal(ATTRIBUTE9, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE10 using the alias name Attribute10.
     * @return the ATTRIBUTE10
     */
    public String getAttribute10() {
        return (String) getAttributeInternal(ATTRIBUTE10);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE10 using the alias name Attribute10.
     * @param value value to set the ATTRIBUTE10
     */
    public void setAttribute10(String value) {
        setAttributeInternal(ATTRIBUTE10, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE11 using the alias name Attribute11.
     * @return the ATTRIBUTE11
     */
    public String getAttribute11() {
        return (String) getAttributeInternal(ATTRIBUTE11);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE11 using the alias name Attribute11.
     * @param value value to set the ATTRIBUTE11
     */
    public void setAttribute11(String value) {
        setAttributeInternal(ATTRIBUTE11, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE12 using the alias name Attribute12.
     * @return the ATTRIBUTE12
     */
    public String getAttribute12() {
        return (String) getAttributeInternal(ATTRIBUTE12);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE12 using the alias name Attribute12.
     * @param value value to set the ATTRIBUTE12
     */
    public void setAttribute12(String value) {
        setAttributeInternal(ATTRIBUTE12, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE13 using the alias name Attribute13.
     * @return the ATTRIBUTE13
     */
    public String getAttribute13() {
        return (String) getAttributeInternal(ATTRIBUTE13);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE13 using the alias name Attribute13.
     * @param value value to set the ATTRIBUTE13
     */
    public void setAttribute13(String value) {
        setAttributeInternal(ATTRIBUTE13, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE14 using the alias name Attribute14.
     * @return the ATTRIBUTE14
     */
    public String getAttribute14() {
        return (String) getAttributeInternal(ATTRIBUTE14);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE14 using the alias name Attribute14.
     * @param value value to set the ATTRIBUTE14
     */
    public void setAttribute14(String value) {
        setAttributeInternal(ATTRIBUTE14, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE15 using the alias name Attribute15.
     * @return the ATTRIBUTE15
     */
    public String getAttribute15() {
        return (String) getAttributeInternal(ATTRIBUTE15);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE15 using the alias name Attribute15.
     * @param value value to set the ATTRIBUTE15
     */
    public void setAttribute15(String value) {
        setAttributeInternal(ATTRIBUTE15, value);
    }

    /**
     * Gets the attribute value for SALESORDER_ID using the alias name SalesorderId.
     * @return the SALESORDER_ID
     */
    public Number getSalesorderId() {
        return (Number) getAttributeInternal(SALESORDERID);
    }

    /**
     * Sets <code>value</code> as attribute value for SALESORDER_ID using the alias name SalesorderId.
     * @param value value to set the SALESORDER_ID
     */
    public void setSalesorderId(Number value) {
        setAttributeInternal(SALESORDERID, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @return the LAST_UPDATE_DATE
     */
    public Date getLastUpdateDate() {
        return (Date) getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @param value value to set the LAST_UPDATE_DATE
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public Number getLastUpdatedBy() {
        return (Number) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Date getCreationDate() {
        return (Date) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate.
     * @param value value to set the CREATION_DATE
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public Number getCreatedBy() {
        return (Number) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for ORG_ID using the alias name OrgId.
     * @return the ORG_ID
     */
    public Number getOrgId() {
        return (Number) getAttributeInternal(ORGID);
    }

    /**
     * Sets <code>value</code> as attribute value for ORG_ID using the alias name OrgId.
     * @param value value to set the ORG_ID
     */
    public void setOrgId(Number value) {
        setAttributeInternal(ORGID, value);
    }

    /**
     * Gets the attribute value for WASH_EMD_PRINT_INVORG using the alias name WashEmdPrintInvorg.
     * @return the WASH_EMD_PRINT_INVORG
     */
    public String getWashEmdPrintInvorg() {
        return (String) getAttributeInternal(WASHEMDPRINTINVORG);
    }

    /**
     * Sets <code>value</code> as attribute value for WASH_EMD_PRINT_INVORG using the alias name WashEmdPrintInvorg.
     * @param value value to set the WASH_EMD_PRINT_INVORG
     */
    public void setWashEmdPrintInvorg(String value) {
        setAttributeInternal(WASHEMDPRINTINVORG, value);
    }

    /**
     * Gets the attribute value for WASH_EMD_PRINT_INV using the alias name WashEmdPrintInv.
     * @return the WASH_EMD_PRINT_INV
     */
    public Number getWashEmdPrintInv() {
        return (Number) getAttributeInternal(WASHEMDPRINTINV);
    }

    /**
     * Sets <code>value</code> as attribute value for WASH_EMD_PRINT_INV using the alias name WashEmdPrintInv.
     * @param value value to set the WASH_EMD_PRINT_INV
     */
    public void setWashEmdPrintInv(Number value) {
        setAttributeInternal(WASHEMDPRINTINV, value);
    }

    /**
     * Gets the attribute value for WASH_TYPE using the alias name WashType.
     * @return the WASH_TYPE
     */
    public String getWashType() {
        return (String) getAttributeInternal(WASHTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for WASH_TYPE using the alias name WashType.
     * @param value value to set the WASH_TYPE
     */
    public void setWashType(String value) {
        setAttributeInternal(WASHTYPE, value);
    }

    /**
     * Gets the attribute value for PRODUCTION_TYPE using the alias name ProductionType.
     * @return the PRODUCTION_TYPE
     */
    public String getProductionType() {
        return (String) getAttributeInternal(PRODUCTIONTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for PRODUCTION_TYPE using the alias name ProductionType.
     * @param value value to set the PRODUCTION_TYPE
     */
    public void setProductionType(String value) {
        setAttributeInternal(PRODUCTIONTYPE, value);
    }

    /**
     * Gets the attribute value for RECEVING_DATE using the alias name RecevingDate.
     * @return the RECEVING_DATE
     */
    public Date getRecevingDate() {
        return (Date) getAttributeInternal(RECEVINGDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for RECEVING_DATE using the alias name RecevingDate.
     * @param value value to set the RECEVING_DATE
     */
    public void setRecevingDate(Date value) {
        setAttributeInternal(RECEVINGDATE, value);
    }


    /**
     * Gets the attribute value for the calculated attribute PocId.
     * @return the PocId
     */
    public BigDecimal getPocId() {
      //  return (Number) getAttributeInternal(POCID);
      //  this.getLineHeaderEOView().getAttribute("PocId");
        return (BigDecimal)getLineHeaderEOView().getAttribute("PocId");
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PocId.
     * @param value value to set the  PocId
     */
    public void setPocId(BigDecimal value) {
        this.getLineHeaderEOView().getAttribute("PocId");
    }

    /**
     * Gets the attribute value for BPO_ID using the alias name BpoId.
     * @return the BPO_ID
     */
    public Number getBpoId() {
        return (Number) getAttributeInternal(BPOID);
    }

    /**
     * Sets <code>value</code> as attribute value for BPO_ID using the alias name BpoId.
     * @param value value to set the BPO_ID
     */
    public void setBpoId(Number value) {
        setAttributeInternal(BPOID, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link ReciveSizeInseemVO.
     */
    public RowIterator getReciveSizeInseemVO() {
        return (RowIterator)getAttributeInternal(RECIVESIZEINSEEMVO);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link LineHeaderEOView.
     */
    public Row getLineHeaderEOView() {
        return (Row)getAttributeInternal(LINEHEADEREOVIEW);
    }

    /**
     * Sets the master-detail link LineHeaderEOView between this object and <code>value</code>.
     */
    public void setLineHeaderEOView(Row value) {
        setAttributeInternal(LINEHEADEREOVIEW, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> RevBPOVO1.
     */
    public RowSet getRevBPOVO1() {
        return (RowSet)getAttributeInternal(REVBPOVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> InvOrgVO1.
     */
    public RowSet getInvOrgVO1() {
        return (RowSet)getAttributeInternal(INVORGVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ProductionTypeVO1.
     */
    public RowSet getProductionTypeVO1() {
        return (RowSet)getAttributeInternal(PRODUCTIONTYPEVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> WashTypeVO1.
     */
    public RowSet getWashTypeVO1() {
        return (RowSet)getAttributeInternal(WASHTYPEVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> BPO_LOV1.
     */
    public RowSet getBPO_LOV1() {
        return (RowSet)getAttributeInternal(BPO_LOV1);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
